<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<ProjectReference Include="..\..\..\BuildingBlocks\BackgroundJobs\MuhammedTask.BuildingBlocks.BackgroundJobs.Quartz\MuhammedTask.BuildingBlocks.BackgroundJobs.Quartz.csproj" />
		<ProjectReference Include="..\..\..\BuildingBlocks\Caching\MuhammedTask.BuildingBlocks.Caching.Redis\MuhammedTask.BuildingBlocks.Caching.Redis.csproj" />
		<ProjectReference Include="..\..\..\BuildingBlocks\Database\MuhammedTask.BuildingBlocks.Database.PostgreSQL\MuhammedTask.BuildingBlocks.Database.PostgreSQL.csproj" />
		<ProjectReference Include="..\..\..\BuildingBlocks\Layers\Infrastructure\MuhammedTask.BuildingBlocks.Persistence\MuhammedTask.BuildingBlocks.Persistence.csproj" />
		<ProjectReference Include="..\..\..\BuildingBlocks\MessageBrokers\MuhammedTask.BuildingBlocks.MessageBrokers.MassTransit.EntityFrameworkCore\MuhammedTask.BuildingBlocks.MessageBrokers.MassTransit.EntityFrameworkCore.csproj" />
		<ProjectReference Include="..\..\..\Host\MuhammedTask.Services.Info\MuhammedTask.Services.Info.csproj" />
		<ProjectReference Include="..\MuhammedTask.Services.CategoryService.Application\MuhammedTask.Services.CategoryService.Application.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="MassTransit.RabbitMQ" />
	</ItemGroup>
</Project>
